# Generated by Django 2.2 on 2019-04-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-activated', 'user']},
        ),
    ]
